version: '3'
services: 
    database:
      image: postgres:14.1-alpine
      restart: always
      container_name: SWE_PostgresDB
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
    databaseservice:
      build: databaseService/.
      ports:
        - "4001:4001"
      image: finnmarkwitz/dhbw-swe-nodejs-databaseservice
      depends_on:
        - "database"
    documentservice:
      build: digitalizationService/.
      ports:
        - "4002:4002"
      image: finnmarkwitz/dhbw-swe-nodejs-documentservice
      depends_on:
        - "database"
    fileservice:
      build: fileService/.
      ports:
        - "4003:4003"
      image: finnmarkwitz/dhbw-swe-nodejs-fileservice
      depends_on:
        - "database"
networks:
  default:
      name: swedocker